ProjectCRUDApp/Controllers/FoodController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectAppLibrary;
using ProjectAppLibrary.Models;
using ProjectAppLibrary.Models.Binding;
using ProjectCRUDApp.Repositories;
using System;

using System.Linq;


namespace ProjectCRUDApp.Controllers
{
    [Route("[Controller]")] //a route property with placeholder
    public class FoodController : Controller
    {
        private IRepositoryWrapper repository;
        public FoodController(IRepositoryWrapper repositoryWrapper)
        {
            repository = repositoryWrapper;

        }

        //READ
        [Route("")]
        public IActionResult Index()
        {
            var allfoods = repository.Food.FindAll();
           // var allfoods = dbContext.Foods.ToList(); //will show all foods on the list
            return View(allfoods);
        }
        [Route("details/{id:int}")] //specify the route by using a placeholder which maps directly what you put in (by recognising the food by its ID)
        public IActionResult Details(int id)
        {
            var foodbyID=repository.Food.FindByCondition(r => r.ID == id).FirstOrDefault(); //using the repository created to access the DbContext in the testing library
           // var foodbyID = dbContext.Foods.FirstOrDefault(r => r.ID == id); //Find the cat by its ID in the database
            return View(foodbyID);
        }



        //CREATE
        [Route("create")]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost("create")] //sends data into a partcular place.
        public IActionResult Create(AddFoodBindingModel bindingModel)
        {
            var foodToCreate = new Food
            {
                Name = bindingModel.Name,
                Cuisine = bindingModel.Cuisine,
                Description = bindingModel.Description,
                PictureURL = "https://i1.wp.com/www.eatthis.com/wp-content/uploads/2020/12/unhealthiest-foods-planet.jpg?fit=1200%2C879&ssl=1", //this will give you a default picture
             CreatedAt = DateTime.Now
            };
            repository.Food.Create(foodToCreate);
            repository.Save();
            return RedirectToAction("Index"); //will return page to index
        }

       
      
        //UPDATE
        [Route("update/{id:int}")]
        public IActionResult Update(int id) //find food and populate the form on this page
        {
             var foodbyID=repository.Food.FindByCondition(r => r.ID == id).FirstOrDefault();
              return View(foodbyID);
        }
        [HttpPost]
        [Route("update/{id:int}")]
        public IActionResult Update(Food food, int id) //pass in ID of food
        { 
            repository.Food.Update(food);
            repository.Save();
            return RedirectToAction("Index"); //will return page to the index
        }


        //DELETE
        [Route("delete/{id:int}")]
        public IActionResult Delete(int id)
        {
            var recipesToDelete = repository.Recipe.FindByCondition(r => r.FoodID == id);
            foreach (var recipe in recipesToDelete)
            { repository.Recipe.Delete(recipe); }
            repository.Save();
            var restaurantsToDelete = repository.Restaurant.FindByCondition(r => r.FoodID == id);
            foreach (var restaurant in restaurantsToDelete)
            { repository.Restaurant.Delete(restaurant); }
            repository.Save();
            var foodToDelete = repository.Food.FindByCondition(r => r.ID == id).FirstOrDefault();
            repository.Food.Delete(foodToDelete); //will remove food from database
            repository.Save();
            return RedirectToAction("Index");
        }




        // RESTAURANT
        [Route("addrestaurant/{foodid:int}")]
        public IActionResult CreateRestaurant(int foodID)
        {
            var food = repository.Food.FindByCondition(r => r.ID == foodID).FirstOrDefault();
            ViewBag.foodName = food.Name;
            return View();
        }
        [HttpPost] //sends data into a particular place.
        [Route("addrestaurant/{foodid:int}")]
        public IActionResult CreateRestaurant(AddRestaurantBindingModel bindingModel, int foodID)
        {
            bindingModel.FoodID = foodID;
            var RestaurantToCreate = new Restaurant
            {
                Name = bindingModel.Name,
                Location = bindingModel.Location,
                NameofDish = bindingModel.NameofDish,
                Delivery = bindingModel.Delivery,
                FoodID = bindingModel.FoodID,
                PictureURL = "https://theresident.wpms.greatbritishlife.co.uk/wp-content/uploads/sites/10/2020/07/Le-Pont-de-la-tour-Terrace-.jpg", 
                ratings = bindingModel.ratings,
                CreatedAt = DateTime.Now
            };

            repository.Restaurant.Create(RestaurantToCreate); //adds the restaurant created to the database
            repository.Save(); //saves the changes
            return RedirectToAction("Index"); //will return page to index
        }

       
        [Route("{id:int}/restaurant")]
        public IActionResult ViewRestaurants(int id)
        {
            var food = repository.Food.FindByCondition(r => r.ID == id).FirstOrDefault();
           var restaurant= repository.Restaurant.FindByCondition(r => r.FoodID == id).ToList();
            ViewBag.foodName = food.Name;
            return View(restaurant);
        }


        // RECIPE
        [Route("addrecipe/{foodid:int}")]
        public IActionResult CreateRecipe(int foodID)
        {
            var food = repository.Food.FindByCondition(r => r.ID == foodID).FirstOrDefault();
            ViewBag.foodName = food.Name;
            return View();
        }
        [HttpPost] //sends data into a particular place.
        [Route("addrecipe/{foodid:int}")]
        public IActionResult CreateRecipe(AddRecipeBindingModel bindingModel, int foodID)
        {
            bindingModel.FoodID = foodID;
            var RecipeToCreate = new Recipe
            {
                RecipeName = bindingModel.RecipeName,
                Ingredients = bindingModel.Ingredients,
                Method = bindingModel.Method,
                Servings = bindingModel.Servings,
                FoodID = bindingModel.FoodID,
                PictureURL = "https://static01.nyt.com/images/2021/01/26/well/well-foods-microbiome/well-foods-microbiome-superJumbo.jpg", 
                LevelofDifficulty = bindingModel.LevelofDifficulty,
                CreatedAt = DateTime.Now
            };

            repository.Recipe.Create(RecipeToCreate); //adds the food created to the database
            repository.Save();//saves the changes
            return RedirectToAction("Index"); //will return page to index
        }
        [Route("{id:int}/recipe")]
        public IActionResult ViewRecipes(int id)
        {
            var food = repository.Food.FindByCondition(r =>r.ID == id).FirstOrDefault();
            var recipe = repository.Recipe.FindByCondition(r => r.Food.ID == id).ToList();
            ViewBag.foodName = food.Name;
            return View(recipe);
        }


    }
}

ProjectCRUDApp/Controllers/RecipeController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectAppLibrary.Models;
using ProjectCRUDApp.Repositories;
using System.Linq;


namespace ProjectCRUDApp.Controllers
{
    [Route("[Controller]")] //a route property with placeholder
    public class RecipeController : Controller
    { 
    private IRepositoryWrapper repository;
    public RecipeController(IRepositoryWrapper repositoryWrapper)
    {
        repository = repositoryWrapper;

    }

    //READ
    [Route("")]
        public IActionResult Index()
        {
            var allRecipes = repository.Recipe.FindAll(); //will show all recipes on the list
            return View(allRecipes);
        }
        [Route("details/{id:int}")] //specify the route by using a placeholder which maps directly what you put in (by recognising the recipe by its ID)
        public IActionResult Details(int id)
        {
            var RecipebyID = repository.Recipe.FindByCondition(r => r.ID == id).FirstOrDefault(); //Find the recipe by its ID in the database
            return View(RecipebyID);
        }

        //UPDATE
        [Route("update/{id:int}")]
        public IActionResult Update(int id) //find recipe and populate the form on this page
            {
            var RecipebyID = repository.Recipe.FindByCondition(r => r.ID == id).FirstOrDefault(); //Find the recipe by its ID in the database
            return View(RecipebyID);
        }
        [HttpPost]
        [Route("update/{id:int}")]
        public IActionResult Update(Recipe recipe, int id) //pass in ID of recipe
        {
            repository.Recipe.Update(recipe);
            repository.Save(); //saves the updated changes
            return RedirectToAction("Index"); //will return page to the index
        }


        //DELETE
        [Route("delete/{id:int}")]
        public IActionResult Delete(int id)
        {
            var RecipeToDelete = repository.Recipe.FindByCondition(r => r.ID == id).FirstOrDefault();
            repository.Recipe.Delete(RecipeToDelete); //will remove recipe from database
            repository.Save();
            return RedirectToAction("Index");
        }
    }
}

ProjectCRUDApp/Controllers/RestaurantsController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectAppLibrary.Models;
using ProjectCRUDApp.Repositories;
using System.Linq;


namespace ProjectCRUDApp.Controllers
{
    [Route("[Controller]")]
    public class RestaurantController : Controller
    {
        private IRepositoryWrapper repository;
        public RestaurantController(IRepositoryWrapper repositoryWrapper)
        {
            repository = repositoryWrapper;

        }


        //READ
        [Route("")]
        public IActionResult Index()
        {
            var allRestaurants = repository.Restaurant.FindAll(); //will show all restaurants on the list
            return View(allRestaurants);
        }
        [Route("details/{id:int}")] //specify the route by using a placeholder which maps directly what you put in (by recognising the restaurant by its ID)
        public IActionResult Details(int id)
        {
            var RestaurantbyID = repository.Restaurant.FindByCondition(r => r.ID == id).FirstOrDefault(); //Find the cat by its ID in the database
            return View(RestaurantbyID);
        }
        

        //UPDATE
        [Route("update/{id:int}")]
        public IActionResult Update(int id) //find restaurant and populate the form on this page
        {
            var RestaurantbyID = repository.Restaurant.FindByCondition(r => r.ID == id).FirstOrDefault(); //Find the restaurant by its ID in the database
            return View(RestaurantbyID);
        }
        [HttpPost]
        [Route("update/{id:int}")]
        public IActionResult Update(Restaurant restaurant, int id) //pass in ID of restaurant
        {
            repository.Restaurant.Update(restaurant);
            repository.Save(); //saves the updated changes
            return RedirectToAction("Index"); //will return page to the index
        }


        //DELETE
        [Route("delete/{id:int}")]
        public IActionResult Delete(int id)
        {
            var RestaurantToDelete = repository.Restaurant.FindByCondition(r => r.FoodID == id).FirstOrDefault();
            repository.Restaurant.Delete(RestaurantToDelete); //will remove restaurant from database
            repository.Save();
            return RedirectToAction("Index");
        }
    }
}

ProjectCRUDApp/Views/Food/Create.cshtml
@model ProjectAppLibrary.Models.Binding.AddFoodBindingModel
@{
    ViewData["Title"] = "Create";
}

<h1>Create New Food item</h1>
<p>
    <a asp-action="Create">Create New</a>
</p>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <!--carries out "create" action-->

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">


                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="Cuisine" class="control-label"></label>
                <input asp-for="Cuisine" class="form-control" />
                <span asp-validation-for="Cuisine" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

  
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index" asp-controller="Food">Back to All Foods</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectCRUDApp/Views/Food/CreateRecipe.cshtml
@model ProjectAppLibrary.Models.Binding.AddRecipeBindingModel
@{
    ViewData["Title"] = "Create Recipe";

}

<h1>Create New @ViewBag.FoodName recipes</h1>
<p>
    <a asp-action="Create">@ViewBag.FoodName Recipes</a>
</p>

<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateRecipe">
            <!--carries out "create" action-->

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RecipeName" class="control-label"></label>
                <input asp-for="RecipeName" class="form-control" />
                <span asp-validation-for="RecipeName" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="Ingredients" class="control-label"></label>
                <textarea asp-for="Ingredients" rows="10" cols="25"></textarea>
                <span asp-validation-for="Ingredients" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Method" class="control-label"></label>
                <textarea asp-for="Method" rows="20" cols="50"></textarea>
                <span asp-validation-for="Method" class="text-danger"></span>
            </div>

            <div>
                <label asp-for="Servings" class="control-label"></label>
                <input asp-for="Servings" class="form-control" />
                <span asp-validation-for="Servings" class="text-danger"></span>
            </div>

            <span asp-validation-for="LevelofDifficulty" class="text-danger"></span>
            <div class="form-group">
                <label asp-for="LevelofDifficulty" class="control-label"></label>
                <select asp-for="LevelofDifficulty" class="form-control">
                    <option value="1">Easy</option>
                    <option value="2">Intermediate</option>
                    <option value="3">Difficult</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index" asp-controller="Food">Back to All Foods</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

ProjectCRUDApp/Views/Food/CreateRestaurant.cshtml
@model ProjectAppLibrary.Models.Binding.AddRestaurantBindingModel
@{
    ViewData["Title"] = "Create Restaurant";
    
}

<h1>Create New Restaurant with @ViewBag.FoodName dishes</h1>
<p>
    <a asp-action="Create">Restaurants with @ViewBag.FoodName Dishes</a>
</p>

<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateRestaurant">
            <!--carries out "create" action-->

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">


                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="NameofDish" class="control-label"></label>
                <input asp-for="NameofDish" class="form-control" />
                <span asp-validation-for="NameofDish" class="text-danger"></span>
            </div>

            <span asp-validation-for="Delivery" class="text-danger"></span>
            <div class="form-group">
                <label asp-for="Delivery" class="control-label"></label>
                <select asp-for="Delivery" class="form-control">
                    <option value="1">Yes</option>
                    <option value="2">No</option>
                </select>
            </div>

            <div class="form-group">
                <label asp-for="ratings" class="control-label"></label>
                <input asp-for="ratings" class="form-control" />
                <span asp-validation-for="ratings" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index" asp-controller="food">Back to All Foods</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectCRUDApp/Views/Food/Details.cshtml
@model ProjectAppLibrary.Models.Food

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PictureURL)
        </dt>
        <dd class="col-sm-10">
            <img src="@Model.PictureURL" style="height:256px;" />
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cuisine)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cuisine)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Update", new { id = Model.ID }) |
    <a asp-action="Index">Back to List</a>
</div>

ProjectCRUDApp/Views/Food/Index.cshtml
@model IEnumerable<ProjectAppLibrary.Models.Food>

@{
    ViewData["Title"] = "Index";
}

<h1>All Foods</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PictureURL)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cuisine)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img src="@item.PictureURL" style="height:128px;" />
               
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cuisine)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
               
                <td>
                    @Html.ActionLink("Edit", "Update", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })|
                    @Html.ActionLink("Add Recipe", "CreateRecipe", new { foodID = item.ID })
                    @Html.ActionLink("View Recipes", "ViewRecipes", new { id = item.ID })
                    @Html.ActionLink("Add Restaurant", "CreateRestaurant", new { foodID = item.ID })
                    @Html.ActionLink("View Restaurants", "ViewRestaurants", new { id = item.ID })


                </td>
            </tr>
        }
    </tbody>
</table>

ProjectCRUDApp/Views/Food/Update.cshtml
@model ProjectAppLibrary.Models.Food
@{
    ViewData["Title"] = "Update";
}

<h1>Update </h1>
<p>Created on @Model.CreatedAt.ToShortDateString()</p>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">


            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">


                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="Cuisine" class="control-label"></label>
                <input asp-for="Cuisine" class="form-control" />
                <span asp-validation-for="Cuisine" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PictureURL" class="control-label"></label>
                <input type='url' asp-for="PictureURL" class="form-control" />
                <span asp-validation-for="PictureURL" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Food">Back to All Foods</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectCRUDApp/Views/Food/ViewRecipes.cshtml
@model IEnumerable<ProjectAppLibrary.Models.Recipe>

@{
    ViewData["Title"] = "Recipes";
}

<h1>@ViewBag.FoodName Recipes</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PictureURL)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RecipeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ingredients)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Method)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Servings)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LevelofDifficulty)
            </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                <img src="@item.PictureURL" style="height:128px;" />
            </td>
         
            <td>
                @Html.DisplayFor(modelItem => item.RecipeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ingredients)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Method)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Servings)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LevelofDifficulty)
            </td>
            >
        </tr>
        }
    </tbody>
</table>
<div>
    <a asp-action="Index" asp-controller="Food">Back to All Foods</a>
</div>
<div>
    <a asp-action="Index" asp-controller="Recipe">View all recipes</a>
</div>

ProjectCRUDApp/Views/Food/ViewRestaurants.cshtml
@model IEnumerable<ProjectAppLibrary.Models.Restaurant>

@{
    ViewData["Title"] = "Restaurants";
}

<h1>Restaurants with @ViewBag.FoodName dishes</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PictureURL)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Delivery)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NameofDish)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ratings)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                <img src="@item.PictureURL" style="height:128px;" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Delivery)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NameofDish)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ratings)
            </td>
           
        </tr>
        }
    </tbody>
</table>
<div>
    <a asp-action="Index" asp-controller="Food">Back to All Foods</a>
</div>
<div>
    <a asp-action="Index" asp-controller="Restaurant">View all restaurants</a>
</div>